-- =============================================================
-- Admin Account Creation Guide
-- CareerTrack Platform
-- =============================================================
-- Default and hardcoded SQL seed credentials have been deprecated and removed
-- to prevent accidental exposure of production credentials.
--
-- To securely create an administrator account, use the environment-driven
-- backend bootstrap script:
--
--   cd backend
--   ADMIN_EMAIL="admin@yourdomain.edu" ADMIN_PASSWORD="your-strong-password" npm run create-admin
--
-- Optional overrides:
--   ADMIN_FIRST_NAME="System"
--   ADMIN_LAST_NAME="Administrator"
--
-- The bootstrap script cryptographically hashes the password with bcrypt (10 rounds)
-- at runtime and ensures no plain-text credentials or reusable default hashes
-- are stored in source code.
--
-- For implementation details, see backend/scripts/createAdmin.js.
-- =============================================================

