-- =============================================================
-- PostgreSQL / Supabase Database Schema
-- Smart Internship & Career Tracker
-- =============================================================
-- INSTRUCTIONS:
-- 1. Open your Supabase Dashboard -> SQL Editor.
-- 2. Create a new query, paste this entire file, and click "Run".
-- =============================================================

-- 1. Create Application Statuses Table & Seed Data
CREATE TABLE IF NOT EXISTS application_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO application_statuses (id, name) VALUES 
(1, 'Applied'),
(2, 'Interview'),
(3, 'Offer'),
(4, 'Rejected')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 2. Create Users Table (Handles both Students and Admins)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')),
    university VARCHAR(255) NULL,
    major VARCHAR(255) NULL,
    graduation_year INT NULL,
    bio TEXT NULL,
    profile_image_url VARCHAR(500) NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    role_title VARCHAR(255) NOT NULL,
    current_status_id BIGINT NOT NULL DEFAULT 1 REFERENCES application_statuses(id),
    date_applied DATE NOT NULL,
    notes TEXT,
    deleted_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create Application Status History Table (for timeline tracking)
CREATE TABLE IF NOT EXISTS application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL REFERENCES application_statuses(id),
    notes TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create Skills Table & Seed Default Skills
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO skills (name) VALUES 
('React'), ('Node.js'), ('Python'), ('Java'), ('TypeScript'), ('AWS'), ('SQL')
ON CONFLICT (name) DO NOTHING;

-- 6. Create Application_Skills Junction Table (Many-to-Many)
CREATE TABLE IF NOT EXISTS application_skills (
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (application_id, skill_id)
);

-- 7. Create Student_Skills Junction Table (Student's personal skills)
CREATE TABLE IF NOT EXISTS student_skills (
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, skill_id)
);

-- 8. Create Feedback & Skill Tag Tables (for Rejection Analysis & Analytics)
CREATE TABLE IF NOT EXISTS feedback_skill_tags (
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (application_id, skill_id)
);

CREATE TABLE IF NOT EXISTS application_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL REFERENCES application_statuses(id),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS application_feedback_skills (
    feedback_id BIGINT NOT NULL REFERENCES application_feedback(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (feedback_id, skill_id)
);

-- 9. SEED DATA: Default Admin Account
-- Pre-generated bcrypt hash for 'AdminPassword123!'
INSERT INTO users (first_name, last_name, email, password_hash, role)
VALUES (
    'Career', 
    'Admin', 
    'admin@university.edu', 
    '$2b$10$w8.3f6.E1T1jV.z2O3eH2e/tFm3bY2B4I2B8D8F4j8B4F8B8B8B8B',
    'admin'
) ON CONFLICT (email) DO UPDATE SET role = 'admin';
