-- =============================================================
-- PostgreSQL / Supabase Database Schema
-- Smart Internship & Career Tracker
-- =============================================================
-- INSTRUCTIONS:
-- 1. Open your Supabase Dashboard -> SQL Editor.
-- 2. Create a new query, paste this entire file, and click "Run".
-- =============================================================

-- 1. Create Application Statuses Table & Seed Data
CREATE TABLE IF NOT EXISTS application_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO application_statuses (id, name) VALUES 
(1, 'Applied'),
(2, 'Interview'),
(3, 'Offer'),
(4, 'Rejected')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 2. Create Users Table (Handles both Students and Admins)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')),
    university VARCHAR(255) NULL,
    major VARCHAR(255) NULL,
    graduation_year INT NULL,
    bio TEXT NULL,
    profile_image_url VARCHAR(500) NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    role_title VARCHAR(255) NOT NULL,
    current_status_id BIGINT NOT NULL DEFAULT 1 REFERENCES application_statuses(id),
    date_applied DATE NOT NULL,
    notes TEXT,
    deleted_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create Application Status History Table (for timeline tracking)
CREATE TABLE IF NOT EXISTS application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL REFERENCES application_statuses(id),
    notes TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create Skills Table & Seed Default Skills
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL DEFAULT 'General',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO skills (name, normalized_name, category) VALUES 
('Python', 'python', 'Programming'),
('JavaScript', 'javascript', 'Programming'),
('TypeScript', 'typescript', 'Programming'),
('Java', 'java', 'Programming'),
('C++', 'c++', 'Programming'),
('C#', 'c#', 'Programming'),
('Go', 'go', 'Programming'),
('SQL', 'sql', 'Programming'),
('MATLAB', 'matlab', 'Engineering Software'),
('Simulink', 'simulink', 'Engineering Software'),
('AutoCAD', 'autocad', 'Engineering Software'),
('SolidWorks', 'solidworks', 'Engineering Software'),
('ANSYS', 'ansys', 'Engineering Software'),
('ETAP', 'etap', 'Engineering Software'),
('PLC', 'plc', 'Industrial Automation'),
('SCADA', 'scada', 'Industrial Automation'),
('HMI', 'hmi', 'Industrial Automation'),
('React', 'react', 'Web & Frameworks'),
('Next.js', 'next.js', 'Web & Frameworks'),
('Node.js', 'node.js', 'Web & Frameworks'),
('Express.js', 'express.js', 'Web & Frameworks'),
('TailwindCSS', 'tailwindcss', 'Web & Frameworks'),
('REST APIs', 'rest apis', 'Web & Frameworks'),
('PostgreSQL', 'postgresql', 'Databases'),
('MongoDB', 'mongodb', 'Databases'),
('AWS', 'aws', 'Cloud & DevOps'),
('Docker', 'docker', 'Cloud & DevOps'),
('Git', 'git', 'Cloud & DevOps'),
('Power BI', 'power bi', 'Data & Analytics')
ON CONFLICT (normalized_name) DO UPDATE SET 
    name = EXCLUDED.name,
    category = EXCLUDED.category;

-- 6. Create Application_Skills Junction Table (Many-to-Many)
CREATE TABLE IF NOT EXISTS application_skills (
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (application_id, skill_id)
);

-- 7. Create Student_Skills Junction Table (Student's personal skills)
CREATE TABLE IF NOT EXISTS student_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    proficiency VARCHAR(30) DEFAULT 'intermediate' CHECK (proficiency IN ('beginner', 'intermediate', 'advanced')),
    source VARCHAR(30) DEFAULT 'manual' CHECK (source IN ('manual', 'ai', 'application', 'resume')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_student_skill UNIQUE (student_id, skill_id)
);

-- 8. Create Feedback & Skill Tag Tables (for Rejection Analysis & Analytics)
CREATE TABLE IF NOT EXISTS feedback_skill_tags (
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (application_id, skill_id)
);

CREATE TABLE IF NOT EXISTS application_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    status_id BIGINT NOT NULL REFERENCES application_statuses(id),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS application_feedback_skills (
    feedback_id BIGINT NOT NULL REFERENCES application_feedback(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (feedback_id, skill_id)
);

-- 9. SEED DATA: Default Admin Account
-- Pre-generated bcrypt hash for 'AdminPassword123!'
INSERT INTO users (first_name, last_name, email, password_hash, role)
VALUES (
    'Career', 
    'Admin', 
    'admin@university.edu', 
    '$2b$10$w8.3f6.E1T1jV.z2O3eH2e/tFm3bY2B4I2B8D8F4j8B4F8B8B8B8B',
    'admin'
) ON CONFLICT (email) DO UPDATE SET role = 'admin';

-- =============================================================
-- 10. Performance Indexes
-- =============================================================
CREATE INDEX IF NOT EXISTS idx_applications_student_id ON applications(student_id);
CREATE INDEX IF NOT EXISTS idx_applications_active ON applications(student_id, current_status_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_application_status_history_lookup ON application_status_history(application_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_application_skills_skill_id ON application_skills(skill_id);
CREATE INDEX IF NOT EXISTS idx_student_skills_skill_id ON student_skills(skill_id);
CREATE INDEX IF NOT EXISTS idx_feedback_skill_tags_skill_id ON feedback_skill_tags(skill_id);
CREATE INDEX IF NOT EXISTS idx_application_feedback_skills_skill_id ON application_feedback_skills(skill_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_skills_name_lower ON skills(LOWER(name));

-- =============================================================
-- 11. Row Level Security (RLS) Configuration
-- =============================================================
ALTER TABLE application_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback_skill_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_feedback_skills ENABLE ROW LEVEL SECURITY;

-- Policies for public catalog tables
DROP POLICY IF EXISTS "Allow read access to application statuses" ON application_statuses;
CREATE POLICY "Allow read access to application statuses" ON application_statuses FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow read access to skills" ON skills;
CREATE POLICY "Allow read access to skills" ON skills FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert skills" ON skills;
CREATE POLICY "Allow authenticated users to insert skills" ON skills FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'service_role');

-- Policies for users
DROP POLICY IF EXISTS "Users can read own profile or admin can read all" ON users;
CREATE POLICY "Users can read own profile or admin can read all" ON users FOR SELECT USING (
    auth.uid()::text = id::text OR auth.jwt() ->> 'role' = 'admin' OR auth.role() = 'service_role'
);

DROP POLICY IF EXISTS "Users can update own profile" ON users;
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (auth.uid()::text = id::text OR auth.role() = 'service_role');

-- Policies for applications
DROP POLICY IF EXISTS "Students can select own applications or admin can read all" ON applications;
CREATE POLICY "Students can select own applications or admin can read all" ON applications FOR SELECT USING (
    student_id::text = auth.uid()::text OR auth.jwt() ->> 'role' = 'admin' OR auth.role() = 'service_role'
);

DROP POLICY IF EXISTS "Students can insert own applications" ON applications;
CREATE POLICY "Students can insert own applications" ON applications FOR INSERT WITH CHECK (
    student_id::text = auth.uid()::text OR auth.role() = 'service_role'
);

DROP POLICY IF EXISTS "Students can update own applications" ON applications;
CREATE POLICY "Students can update own applications" ON applications FOR UPDATE USING (
    student_id::text = auth.uid()::text OR auth.role() = 'service_role'
);

DROP POLICY IF EXISTS "Students can delete own applications" ON applications;
CREATE POLICY "Students can delete own applications" ON applications FOR DELETE USING (
    student_id::text = auth.uid()::text OR auth.role() = 'service_role'
);

-- Policies for history
DROP POLICY IF EXISTS "Students can select own status history" ON application_status_history;
CREATE POLICY "Students can select own status history" ON application_status_history FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM applications 
        WHERE applications.id = application_status_history.application_id 
          AND (applications.student_id::text = auth.uid()::text OR auth.jwt() ->> 'role' = 'admin')
    ) OR auth.role() = 'service_role'
);

DROP POLICY IF EXISTS "Students can insert status history for own applications" ON application_status_history;
CREATE POLICY "Students can insert status history for own applications" ON application_status_history FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM applications 
        WHERE applications.id = application_status_history.application_id 
          AND applications.student_id::text = auth.uid()::text
    ) OR auth.role() = 'service_role'
);

-- Policies for student skills
DROP POLICY IF EXISTS "Students can manage own skills" ON student_skills;
CREATE POLICY "Students can manage own skills" ON student_skills FOR ALL
    USING (student_id::text = auth.uid()::text OR auth.role() = 'service_role')
    WITH CHECK (student_id::text = auth.uid()::text OR auth.role() = 'service_role');

-- Policies for application skills
DROP POLICY IF EXISTS "Students can manage own application skills" ON application_skills;
CREATE POLICY "Students can manage own application skills" ON application_skills FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM applications 
            WHERE applications.id = application_skills.application_id 
              AND (applications.student_id::text = auth.uid()::text OR auth.jwt() ->> 'role' = 'admin')
        ) OR auth.role() = 'service_role'
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM applications 
            WHERE applications.id = application_skills.application_id 
              AND applications.student_id::text = auth.uid()::text
        ) OR auth.role() = 'service_role'
    );

